# Generated by Django 4.2.3 on 2023-12-22 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff_model',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
