# Generated by Django 4.2.3 on 2023-12-23 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0004_subject_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionyear',
            name='session_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sessionyear',
            name='session_start',
            field=models.DateField(),
        ),
    ]
