# Generated by Django 4.2.3 on 2023-12-24 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0006_alter_student_model_session_year_id_staff_leave'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Staff_Leave',
            new_name='Staff_Leave_model',
        ),
    ]
