# Generated by Django 4.2.3 on 2024-01-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0012_result_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance_report_model',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
