# Generated by Django 4.2.3 on 2024-01-02 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0013_attendance_report_model_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance_report_model',
            name='status',
        ),
    ]
